- hosts: localhost
  become: true
  tasks:
    - name: Update cache
      apt: 
        update_cache: true
    - name: Install tools
      apt:
        name: ["curl", "git"]
    - name: Install tmux
      apt: 
        name: tmux
        state: present
    - name: Install neovim from custom repo
      apt_repository:
        repo: 'ppa:neovim-ppa/unstable'
        state: present
      become: true
    - name: Install neovim
      package:
        name: neovim
        state: present
    - name: Install ZSH
      apt: 
        name: zsh
        state: present
    - name: Install Oh My Zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -q)"
    - name: Install Oh My Zsh - FZF
      shell: sh -c "$(git clone https://github.com/unixorn/fzf-zsh-plugin.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-zsh-plugin)"
