call plug#begin()

" " Syntax highlighting for many languages
Plug 'sheerun/vim-polyglot'

" " Code formatting
Plug 'editorconfig/editorconfig-vim'

" " Colorschemes
Plug 'morhetz/gruvbox'

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install() }}
Plug 'christoomey/vim-tmux-navigator'

Plug 'jiangmiao/auto-pairs'
Plug 'farmergreg/vim-lastplace'
Plug 'scrooloose/nerdtree'

Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-fugitive'

Plug 'Galooshi/vim-import-js'
Plug 'janko-m/vim-test'

call plug#end()

" " Colors
set termguicolors
let g:gruvbox_italic=1
colorscheme gruvbox

set encoding=utf8
scriptencoding utf8
set autoread
set hidden
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
syntax enable
set foldcolumn=1
set cursorline
set scrolloff=15
set softtabstop=4
set backspace=indent,eol,start
set autoindent 
set nowrap
set showmatch
set incsearch
set hlsearch
set ignorecase
set smartcase
set noshowmode
set splitright
set splitbelow
set lazyredraw
set ttyfast

if has('persistent_undo')
    set undofile 
    set undodir=~/.vim/undo
endif

set directory=~/.vim/swap

:let mapleader = "\<space>"

" Close NERDTree and open vimrc
noremap <leader>, :NERDTreeClose<CR>:e ~/.vimrc<CR>
" Clear hightlight search
noremap <leader><leader> :nohlsearch<CR>

nmap <leader>a :Commands<CR>
nmap <leader>o :GFiles<CR>
nmap <leader>f :Ag<CR>
nmap <leader>e :History<CR>
nmap <leader>b :Buffers<CR>
nmap <leader>t :NERDTreeVCS<CR>
" nmap <leader>d :ALEGoToDefinition<CR>
" nmap <leader>ll :ALELint<CR>
" nmap <leader>ln :ALENext<CR>
" nmap <leader>lp :ALEPrevious<CR>
nmap <leader>\ :vsplit<CR>
nmap <leader>- :split<CR>

augroup BufferWrite
autocmd!
autocmd BufWritePost .vimrc silent so %
augroup END

augroup BgHighlight
    autocmd!
    autocmd WinEnter * set cul
    autocmd WinLeave * set nocul
augroup END

" NERDTree configuration
let NERDTreeShowHidden=1
let NERDTreeWinSize=60
let NERDTreeQuitOnOpen=1
let g:NERDTreeNodeDelimiter = "\u00a0"

" Smaller updatetime for CursorHold & CursorHoldI
set updatetime=300

" " ALE configuration
" let b:ale_fixers = ['eslint', 'prettier']
" let g:ale_fix_on_save = 1

