call plug#begin()

" Syntax highlighting for many languages
Plug 'sheerun/vim-polyglot'
Plug 'jparise/vim-graphql'
Plug 'posva/vim-vue'

" Code formatting
Plug 'editorconfig/editorconfig-vim'

" Colorschemes
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
" Plug 'edkolev/tmuxline.vim'

Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'mileszs/ack.vim'
Plug 'christoomey/vim-tmux-navigator'

Plug 'jiangmiao/auto-pairs'
Plug 'farmergreg/vim-lastplace'
Plug 'editorconfig/editorconfig-vim'
Plug 'scrooloose/nerdtree'
Plug 'lvht/phpcd.vim', { 'for': 'php', 'do': 'composer install' }
" Plug 'valloric/youcompleteme'
Plug 'Shougo/deoplete.nvim'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'Galooshi/vim-import-js' " npm install -g import-js
Plug 'ternjs/tern_for_vim'

Plug 'stephpy/vim-php-cs-fixer'

Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-sleuth'
Plug 'tpope/vim-unimpaired'

Plug 'airblade/vim-gitgutter'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tpope/vim-fugitive'

Plug 'sbdchd/neoformat'
Plug 'w0rp/ale'

call plug#end()

set encoding=utf-8
scriptencoding utf-8
set autoread
set hidden
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
syntax enable
set number
set relativenumber
set lazyredraw
set cursorline
set scrolloff=15
set softtabstop=4
set backspace=indent,eol,start
set autoindent
set nowrap
set showmatch
set colorcolumn=100
set incsearch
set hlsearch
set ignorecase
set smartcase
set noshowmode
set splitright
set splitbelow
set lazyredraw
set ttyfast

if has('persistent_undo')
    set undofile 
    set undodir=~/.vim/undo
endif

set directory=~/.vim/swap

:let mapleader = "\<space>"

" Close NERDTree and open vimrc
noremap <leader>, :NERDTreeClose<CR>:e ~/.vimrc<CR>
" Clear hightlight search
noremap <leader><leader> :nohlsearch<CR>

" nmap <leader>o :Files<CR>
nmap <leader>o :GFiles<CR>
nmap <leader>e :History<CR>
nmap <leader>b :Buffers<CR>
nmap <leader>s :RipGrep<CR>
nmap <leader>t :NERDTreeToggle<CR>
nmap <leader>i :ImportJSFix<CR>
nmap <leader>p :Neoformat<CR>
nmap <leader>ll :ALELint<CR>
nmap <leader>ln :ALENext<CR>
nmap <leader>lp :ALEPrevious<CR>

let g:rg_command = '
  \ rg --column --line-number --no-heading --fixed-strings --ignore-case --no-ignore --hidden --follow --color "always"
  \ -g "*.{js,json,php,md,styl,jade,html,config,py,cpp,c,go,hs,rb,conf}"
  \ -g "!{.git,node_modules,vendor}/*" '

command! -bang -nargs=* RipGrep call fzf#vim#grep(g:rg_command .shellescape(<q-args>), 1, <bang>0)

augroup BufferWrite
autocmd!
" autocmd BufWritePre *.js silent ImportJSFix
" autocmd BufWritePre *.js silent Neoformat
autocmd BufWritePost .vimrc silent so %
" autocmd BufWritePre *.php silent call PhpCsFixerFixFile()
augroup END

" augroup Colors
"     autocmd!
"     autocmd Focus

" let g:deoplete#enable_at_startup = 1
" let g:deoplete#ignore_sources = get(g:, 'deoplete#ignore_sources', {})
" let g:deoplete#ignore_sources.php = ['omni']

" Colors
set background=dark
colorscheme gruvbox
let g:airline_theme='zenburn'
set laststatus=2

" NERDTree configuration
let NERDTreeShowHidden=1
let NERDTreeWinSize=60

" ALE configuration
let g:ale_fixers = {}
let g:ale_fixers['javascript'] = ['prettier']
let g:ale_fixers['php'] = ['prettier']
let g:ale_completion_enabled = 1

" set statusline=%f%r
" set statusline+=\ 
" set statusline+=%y
" set statusline+=%=
" set statusline+=%l/%L
" set statusline+=%{fugitive#statusline()}


