# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export PATH="/usr/local/sbin:$PATH"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="spaceship"

plugins=(git)

# User configuration
source $ZSH/oh-my-zsh.sh

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export EDITOR='vim'
export SSH_KEY_PATH="~/.ssh/dsa_id"
export PATH="$(brew --prefix homebrew/php/php71)/bin:$PATH"
export JIRA_HOME=$HOME/jira

# Aliases
alias vim="/usr/local/Cellar/vim/8.1.0100_2/bin/vim"

# Project shortcuts
alias sanskrit="/Users/edgarpost/Projects/mediamonks^mediamonks-sanskrit"
alias airforce="/Users/edgarpost/Projects/gsd-m-airforce-com/deploy"
alias kheera-npm="/Users/edgarpost/Projects/kheera"
alias kheera-ui="/Users/edgarpost/Projects/kheera-ui"
alias kheera-mock-project="/Users/edgarpost/Projects/kheera-mockproject"
alias twitter-media="/Users/edgarpost/Projects/twitter-mediatwitter-com/source/adobe-experience-manager/src/maven/twitter-aem-modules/media-twitter-project/media-ui/src/main/webpack"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# Set Spaceship ZSH as a prompt
autoload -U promptinit; promptinit
prompt spaceship
